spring:
  r2dbc:
    dialect: POSTGRES
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

server:
  port: 8080